# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import challenge_pb2 as challenge__pb2


class RemoteExecuteAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/com.github.anight.mysticchallenge.RemoteExecuteAPI/Execute',
                request_serializer=challenge__pb2.RequestExecute.SerializeToString,
                response_deserializer=challenge__pb2.ResponseExecute.FromString,
                )


class RemoteExecuteAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteExecuteAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=challenge__pb2.RequestExecute.FromString,
                    response_serializer=challenge__pb2.ResponseExecute.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.github.anight.mysticchallenge.RemoteExecuteAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteExecuteAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.github.anight.mysticchallenge.RemoteExecuteAPI/Execute',
            challenge__pb2.RequestExecute.SerializeToString,
            challenge__pb2.ResponseExecute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
